apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mcpo.yaml
  - pvc.yaml
  - service.yaml

configMapGenerator:
  - name: mcpo-config
    files:
      - files/config.json
