apiVersion: v1
kind: Service
metadata:
  name:  heimdall
  labels:
    app: heimdall
spec:
  selector:
    app:  heimdall
  type: ClusterIP
  ports:
    - name:  http
      port:  80
      protocol: TCP 
