apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - piper/deployment.yaml
  - piper/imageupdateautomation.yaml
  - piper/pvc.yaml
  - piper/service.yaml
  - whisper/deployment.yaml
  - whisper/imageupdateautomation.yaml
  - whisper/pvc.yaml
  - whisper/service.yaml
