apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - namespace.yaml
  - postgres-pvc.yaml
  - postgres-secrets.sops.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - keycloak-secrets.yaml
  - keycloak-statefulset.yaml
  - keycloak-service.yaml
