apiVersion: v1
kind: Service
metadata:
  name:  piper
  namespace: homeassistant
spec:
  selector:
    app:  piper
  type: ClusterIP
  ports:
    - port:  10200
      protocol: TCP 
      targetPort: 10200
