---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: ollama
  namespace: flux-system
spec:
  image: docker.io/ollama/ollama
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: ollama-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ollama
  policy:
    semver:
      range: ">=0.13.x"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: ollama-image-update
  namespace: flux-system
spec:
  interval: 6h
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
    push:
      branch: fluxcd-ollama-image-update
  update:
    path: ./flux/apps/ai/ollama
