---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ollama

resources:
  - cert.yaml
  - ingress.yaml
  - namespace.yaml
  - ollama.yaml
  - pvc.yaml
  - service.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - imageupdateautomation.yaml
