apiVersion: apps/v1
kind: Deployment
metadata:
  name: wyoming-whisper
  namespace: homeassistant
  labels:
    app: whisper
spec:
  selector:
    matchLabels:
      app: whisper
  replicas: 1
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
      - name: wyoming-whisper
        image: rhasspy/wyoming-whisper:2.5.0 # {"$imagepolicy": "flux-system:whisper-policy"}
        args: ["--model", "tiny-int8", "--language", "en"]
        ports:
        - containerPort: 10300
        volumeMounts:
        - mountPath: /data
          name: data
        resources:  {}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: whisper-data
