---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: whisper
  namespace: flux-system
spec:
  image: docker.io/rhasspy/wyoming-whisper
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: whisper-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: whisper
  policy:
    semver:
      range: ">=2.5.0"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: whisper-image-update
  namespace: flux-system
spec:
  interval: 6h
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
    push:
      branch: fluxcd-whisper-image-update
  update:
    path: ./flux/apps/smart-home/wyoming/whisper
