apiVersion: v1
kind: Service
metadata:
  name:  whisper
  namespace: homeassistant
spec:
  selector:
    app:  whisper
  type: ClusterIP
  ports:
    - port:  10300
      protocol: TCP 
      targetPort: 10300
