apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 1h
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      version: 81.5.0
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
