apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  # - grafana-data-source.yaml
  - grafana-httproute.yaml
  - helm-release.yaml
  - helm-repo.yaml

configMapGenerator:
  - name: helm-values
    files:
      - files/values.yaml
