---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: music-assistant
  namespace: flux-system
spec:
  image: ghcr.io/music-assistant/server
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: music-assistant-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: music-assistant
  policy:
    semver:
      range: ">=2.5.8"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: music-assistant-image-update
  namespace: flux-system
spec:
  interval: 6h
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
    push:
      branch: fluxcd-music-assistant-image-update
  update:
    path: ./flux/apps/smart-home/music-assistant
