---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanboard
  labels:
    app: kanboard
spec:
  selector:
    matchLabels:
      app: kanboard
  replicas: 1
  template:
    metadata:
      labels:
        app: kanboard
    spec:
      containers:
        - name: kanboard
          image: docker.io/kanboard/kanboard:v1.2.47 # {"$imagepolicy": "flux-system:kanboard-policy"}
          ports:
            - name: web-ui
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck.php
              port: web-ui
            initialDelaySeconds: 30
            periodSeconds: 60
          volumeMounts:
            - mountPath: /var/www/app/data
              name: kanboard-data
              readOnly: False
          resources: {}
      restartPolicy: Always
      volumes:
        - name: kanboard-data
          persistentVolumeClaim:
            claimName: kanboard-data
