apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanboard
  namespace: kanboard
spec:
  ingressClassName: nginx
  rules:
  - host: kanboard.${GLOBAL_DOMAIN}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kanboard
            port:
              number: 80
  tls:
    - hosts:
        - kanboard.${GLOBAL_DOMAIN}
      secretName: kanboard-tls
