apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kanboard
resources:
  - cert.yaml
  - deployment.yaml
  - imageupdateautomation.yaml
  - ingress.yaml
  - namespace.yaml
  - pvc.yaml
  - service.yaml