apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wallos
  namespace: wallos
spec:
  ingressClassName: nginx
  rules:
  - host: wallos.${GLOBAL_DOMAIN}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: wallos
            port:
              number: 80
  tls:
    - hosts:
        - wallos.${GLOBAL_DOMAIN}
      secretName: wallos-tls
