---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: uptime-kuma
  namespace: flux-system
spec:
  image: ghcr.io/louislam/uptime-kuma
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: uptime-kuma-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: uptime-kuma
  policy:
    semver:
      range: ">=2.0.2"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: uptime-kuma-image-update
  namespace: flux-system
spec:
  interval: 6h
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
    push:
      branch: fluxcd-uptime-kuma-image-update
  update:
    path: ./flux/apps/uptime-kuma
